pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
  case_sensitive: False
- name: "SpacyTokenizer"
  "intent_tokenization_flag": False
  "intent_split_symbol": "_"
  "token_pattern": None
- name: "SpacyFeaturizer"
  "pooling": "mean"
- name: "RegexFeaturizer"
  "case_sensitive": True
  "use_word_boundaries": True
#- name: "ner_duckling_http"
#  url: "http://duckling.rasa.com:8000"
#  dimensions: ["number","distance", "time", "amount-of-money"]
  #dimensions: ["time", "number", "temperature", "ordinal", "distance", "volume", "amount-of-money", "duration", "email", "url", "phone-number"]
#  locale: "en_US"
#  timezone: "Europe/Paris"
- name: "CRFEntityExtractor"
  "BILOU_flag": True
  "features": [
    ["low", "title", "upper"],
    [
      "bias",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
      "pattern",
    ],
    ["low", "title", "upper"]]
  "max_iterations": 50
  "L1_c": 0.1
  "L2_c": 0.1
  "featurizers": []
- name: "SpacyEntityExtractor"
  dimensions: ["PERSON", "GPE", "ORG", "PRODUCT"]
- name: "RegexEntityExtractor"


