language: hi
pipeline:
  - name: SpacyNLP
    model: "hi_model" 
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: LexicalSyntacticFeaturizer
  - name: "RegexFeaturizer"
    "case_sensitive": True
    # use match word boundaries for lookup table
    "use_word_boundaries": True
    #- name: RegexEntityExtractor
    #case_sensitive: False
     # use lookup tables to extract entities
     #use_lookup_tables: True
    # use regexes to extract entities
    #use_regexes: True
    # use match word boundaries for lookup table
    #"use_word_boundaries": True

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: SpacyEntityExtractor
  - name: "CRFEntityExtractor"
    "BILOU_flag": False
    "features": [
    ["low", "title", "upper"],
    [
      "bias",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
      "pattern",
    ],
    ["low", "title", "upper"]]
    "max_iterations": 75
    "L1_c": 0.15
    "L2_c": 0.15
    "featurizers": []

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
